### ISSUE TITLE
Where are the settings?

### ISSUE THREAD

**Issue by DesktopMasters** [fastfinge/adispeak#25]
The instructions say I can configure AdiSpeak from the options in AdiIRC but I see no options pertaining to this app.  I did find what I believe is the config file.  I set everything in that file to "false" but still, whenever I go into a channel I hear "Entering #channel".  how do I turn that off?  How do I configure what voice it is using?

**Comment by fastfinge** [comment]
You configure the voice from within the Windows control panel if you're using SAPI. Or it autodetects your screen reader. You can't currently turn off the focus messages.
