### ISSUE TITLE
The Config System

### ISSUE THREAD

**Issue by fastfinge** [fastfinge/adispeak#9]
OK, this is what I think the config system is going to look like.  

1.  We'll write code for [WindowOpened Delegate](https://adiirc.github.io/apiv2/generated/html/897e4e17-81e2-7b33-fb1f-9653e6ec4270.htm) that checks to see if a section in the ini file exists named the name of the server, plus the name of the window. Ini files don't allow spaces, so we need to trim them from the string before checking.  If a section for that window doesn't exist, we'll create it, and copy all of the keys out of global to serve as the default settings for that window.  

2.  When any message comes in, we'll check to see if ["global"]["speech"] is "true", if ["global"]["MessageType"] is "true", if ["WindowName"]["speech"] is "true", and if ["WindowName"]["MessageType"] is "true". If all of those things are "true", then we'll output the message.

3.  We'll create a set of menus under commands under speech in the menu bar, one called global, and one called active window. Checking or unchecking items in those menus will update the config.

The one issue with this is that over time, as people open more and more different windows, the ini file is going to get larger and larger. How can we clean this up? Do we care? I'm not sure.

Can you think of a better way to do this?  I don't like copying the global config over and over again. But I don't want to check if a particular section of the ini exists in every output function, and then check if a particular key in that section exists. That will probably lag speech doing it over and over and over again with every message.

I haven't started on any of the above three tasks; I'll wait to see if you have any input. Or if not, if you want to take on any of them. @arfy8820

**Comment by arfy8820** [comment]
I agree, this seems like the best way to do things, slightly inefficient as it is. To try and not confuse things too much, is there a way we can have everything from global copied minus the sapi setting?

**Comment by fastfinge** [comment]
Right now I'm just including the sapi key.  I guess you could remove it if you want; it doesn't make much difference either way. Just in the window open function right after the merge, call .remove or whatever.

**Comment by fastfinge** [comment]
This still refers to ini files and we're using json and Oh God I don't even know anymore. I spent like half an hour trying to figure out how to add menu items and couldn't. There are keyboard commands, so I'm calling this done.
